### ISSUE TITLE
Date slider/filter 

### ISSUE THREAD

**Issue by Anniethedumpling** [trycrmr/covid-data-discovery#100]
Consider building in a date slider feature since this covid thing is dragging out. I might want to just see April and may since that's when the most cases are. Would want to see the rest of the chart snap back and forth and the relativity change with the date change as well so the line chart doesn't seem to be too small or too large.

**Comment by trycrmr** [comment]
Would this suffice? https://codepen.io/plotly/pen/WwXEoV 

If so, it's an easy add via plotly's API :+1: :+1:

**Comment by Anniethedumpling** [comment]
That's pretty cool!

**Comment by trycrmr** [comment]
The first gif shows where the dev on this is (code at https://github.com/trycrmr/covid-data-discovery/tree/100-plotly-date-slider ). The second gif highlights some issues with keeping the visual slider bit below the chart (it hides the legend, which means the show/hide bit of clicking on something in the legend can't be accessed), and using the buttons to jump to a certain date range (has bugs with the lines+markers chart; Works with the bar chart, but the bar chart is a confusing way to represent a cumulative count, the main "Cases" & "Deaths" metric). On mobile it might get confusing for first-time users if they try to scroll and zoom in on accident, but showing the plotly menu buttons with the reset axes at all times should help folks reset their bearings after zooming in, whether purposefully or accidentally. 

1)
![100-zoom-in-changes](https://user-images.githubusercontent.com/6002123/81613287-2dc89700-93ac-11ea-8d05-ead9149db763.gif)

2) 
![date-slider-attempt](https://user-images.githubusercontent.com/6002123/81613582-be06dc00-93ac-11ea-9d59-0420c4dafa48.gif)

**Comment by trycrmr** [comment]
Deployed with https://github.com/trycrmr/covid-data-discovery/releases/tag/1.4.0

**Comment by trycrmr** [comment]
Well well well, this doesn't work so well on mobile in the wild.

**Comment by trycrmr** [comment]
Adding #114 would help resolve this issue. Some way to manually input a date range. Then, on mobile, folks can do that.

**Comment by trycrmr** [comment]
Played with this a little more this morning, and it appears if the user scrolls, then attempts to zoom on the chart, the chart doesn't respond. I expect this is because the svg doesn't have the browser focus, so that interaction isn't tracked. I tested on mobile chrome browser. 

Since that's more of a bug to this existing feature, here's an issue to track this bug https://github.com/trycrmr/covid-data-discovery/issues/117 , and I'll close this issue. Put another way, this feature exists now, but there is a bug with it.
