### ISSUE TITLE
Try using plotly's different functions besides newPlot for perf gains 

### ISSUE THREAD

**Issue by trycrmr** [trycrmr/covid-data-discovery#121]
https://plotly.com/javascript/plotlyjs-function-reference/#plotlyupdate
^"This function has comparable performance to Plotly.react and is faster than redrawing the whole plot with Plotly.newPlot."

**Comment by trycrmr** [comment]
Interestingly enough, the slowest execution of newPlot() was faster than the fastest execution of update(). Some implementation details of the API make using update() difficult in the context. 

- Identifying individual traces to update is done with the index of that trace in plotly's data array for that plot. In this context the user basically adds and removes traces depending on the filters they want. Identifying what trace to update would require separate state management of what index in plotly's data array reflect what data. 
- Also, the user isn't provided an interface for changing a specific trace. Basically every action a user takes either adds or removes a trace. Updating an individual trace doesn't happen at this time. 

Without adding separate state management to map data indexes to what trace & filter set reflects that data, the only option is remove all traces, then add back traces. That forces the execution time of using update() and associated functions to increase at a faster rate as more traces are added to the chart than just using newPlot() to construct a completely new chart. 

See the image below. All localhost:239 timer calls reflect the entirety of the time it takes for plotly to update the chart. The window on the left uses update() and associated functions, while the right uses newPlot() . It's clear newPlot() is the faster option for this context. 

![image](https://user-images.githubusercontent.com/6002123/82126307-e0687300-9779-11ea-9147-fd628e5ee731.png)

**Comment by leeoniya** [comment]
some other alternatives: https://github.com/leeoniya/uPlot#performance

**Comment by trycrmr** [comment]
Oh wow @leeoniya thanks! Opened a new issue to track experimentation https://github.com/trycrmr/covid-data-discovery/issues/122
